#!/usr/bin/env bash
# This script transfers a file from the client to the target server
# Or more accurately, copies the file. The file on the client remains intact

if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
