#!/usr/bin/env bash
# This script automates installation of nginx and redirection of a webpage

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permenant;" /etc/nginx/sites-available/default
service nginx restart
