#!/usr/bin/env bash
# This script prints the word "Best School" 10 times using the while loop and "Hi" on the 9th loop
i=1;
while [[ $i -lt 11 ]]
do
	echo "Best School"
	if [[ $i -eq 9 ]]
	then
		echo "Hi"
		fi
		((i++))
done
