#!/usr/bin/env bash
# This script tells a... story... using the /etc/passwd file
while IFS=: read -r username password uid gid info home_dir cmd
do
	echo "The user $username is part of the $gid gang, lives in $home_dir and rides $cmd. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
